:concurrency: 1
:scheduler:
  :schedule:
    retrieve_device_status_job:
      every: 30 seconds
      class: RetrieveDeviceStatusJob
    send_report_to_central_server_job:
      every: 30 seconds
      class: SendReportToCentralServerJob